version: "3.8"
services:

  postgres:
    container_name: minitwit-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d minitwit-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: minitwit-webapp
    container_name: minitwit-web
    depends_on:
      postgres:
        condition: service_healthy
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        db_user: ${DB_USER}
        db_password: ${DB_PASSWORD}
        db_host: ${DB_HOST}
        db_name: ${DB_NAME}
        db_port: ${DB_PORT}
        port: ${PORT}
        session_key: ${SESSION_KEY}
        gin_mode: ${GIN_MODE}
        BUILDKIT_PROGRESS: plain docker-compose build
    ports:
      - '8080:8080'
    restart: always
    links:
      - postgres:database