apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://164.92.240.232:9090  # This should be configurable in some way??? The ip address should not be hardcoded
  orgId: 1
  uid: "TSwyULa4z"
  user: ""
  database: ""
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     httpMethod: "POST"
  version: 1
  readOnly: false
  editable: true
- name: Loki
  type: loki
  access: proxy
  url: http://164.92.240.232:3100  # This should be configurable in some way??? The ip address should not be hardcoded
  orgId: 1
  uid: "n_Rr2LP4k"
  user: ""
  database: ""
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: false
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     httpMethod: "POST"
  version: 1
  readOnly: false
  editable: true