{
 "title": "Endpoints",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "POST /sim/msgs/:username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "minitwit_endpoint_calls{name=\"/sim/msgs/:username\", method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MiniTwit App System Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GET /sim/msgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "minitwit_endpoint_calls{name=\"/sim/msgs\", method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST /add_message",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "minitwit_endpoint_calls{name=\"/add_message\", method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET /sim/latest",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "minitwit_endpoint_calls{name=\"/sim/latest\", method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}