version: "3.8"
services:

  postgres:
    container_name: minitwit-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d minitwit-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: minitwit-webapp
    container_name: minitwit-web
    depends_on:
      postgres:
        condition: service_healthy
    build: 
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - '8080:8080'
    restart: always
    links:
      - postgres:database