version: "3.8"
services:

  postgres:
    image: postgres
    container_name: minitwit-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d minitwit-db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - minitwit-net

  web:
    image: minitwit-webapp
    build: 
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    container_name: minitwit-web
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    restart: always
    links:
      - postgres:database
    networks:
      - minitwit-net
  
  frontend:
    build: 
      context: ../
      dockerfile: ./docker/frontend/Dockerfile
      target: deploy-static
    ports:
      - "3000:80"
    networks:
      - minitwit-net

networks:
  minitwit-net:
    name: minitwit-net
    driver: bridge