name: Minitwit Automated Testing

on:
  push:
    branches:
      - development
  workflow_run:
    workflows:
      - "Automated Testing"
    types:
      - completed
    branches:
      - development
      

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: ShellCheck
          uses: ludeeus/action-shellcheck@2.0.0
