---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
      - master
      - development
      - enabler/test-workflow
  # allow manual triggers for now too
  workflow_dispatch:
    manual: true
''
