---
name: Minitwit Pipeline

on:
  push:
    branches:
      - enabler/pipeline
  workflow_dispatch:

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD
# SSH_USER
# SSH_KEY
# SSH_HOST

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Run a one-line script
          run: echo Hello, world!

